CREATE TABLE IF NOT EXISTS USER(
  id_user INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(30) NOT  NULL,
  bio TEXT,
  phone VARCHAR(12) NOT NULL,
  email VARCHAR(50) NOT NULL,
  photo VARCHAR(256)
);